/**
 * S&P 500 companies with approximate market caps (billions USD, May 2026).
 * This is the authoritative list for H/L mode — same universe as the ticker
 * Wordle game. All ~460 entries (dot-class shares excluded).
 *
 * Randomisation uses Fisher-Yates and a session queue so every company
 * appears before any repeats, and the same ticker never appears twice in a row.
 */

export const SP500_COMPANIES = [
  // ── Communication Services ────────────────────────────────────────────────
  { symbol: 'CHTR',  name: 'Charter Communications',    marketCap:  45 },
  { symbol: 'CMCSA', name: 'Comcast',                    marketCap: 140 },
  { symbol: 'EA',    name: 'Electronic Arts',            marketCap:  35 },
  { symbol: 'FOXA',  name: 'Fox Corporation (A)',        marketCap:  22 },
  { symbol: 'FOX',   name: 'Fox Corporation (B)',        marketCap:  20 },
  { symbol: 'GOOG',  name: 'Alphabet (Class C)',         marketCap: 2100 },
  { symbol: 'GOOGL', name: 'Alphabet (Class A)',         marketCap: 2100 },
  { symbol: 'LYV',   name: 'Live Nation',                marketCap:  25 },
  { symbol: 'META',  name: 'Meta Platforms',             marketCap: 1600 },
  { symbol: 'NFLX',  name: 'Netflix',                    marketCap: 380 },
  { symbol: 'NWSA',  name: 'News Corp (A)',              marketCap:  13 },
  { symbol: 'NWS',   name: 'News Corp (B)',              marketCap:  12 },
  { symbol: 'OMC',   name: 'Omnicom Group',              marketCap:  16 },
  { symbol: 'PSKY',  name: 'Paramount Skydance',         marketCap:  15 },
  { symbol: 'SATS',  name: 'EchoStar',                   marketCap:   3 },
  { symbol: 'T',     name: 'AT&T',                       marketCap: 175 },
  { symbol: 'TMUS',  name: 'T-Mobile',                   marketCap: 265 },
  { symbol: 'VZ',    name: 'Verizon',                    marketCap: 165 },
  { symbol: 'WBD',   name: 'Warner Bros. Discovery',     marketCap:  22 },

  // ── Consumer Discretionary ────────────────────────────────────────────────
  { symbol: 'ABNB',  name: 'Airbnb',                     marketCap:  85 },
  { symbol: 'AMZN',  name: 'Amazon',                     marketCap: 2200 },
  { symbol: 'APTV',  name: 'Aptiv',                      marketCap:   8 },
  { symbol: 'AZO',   name: 'AutoZone',                   marketCap:  45 },
  { symbol: 'BBY',   name: 'Best Buy',                   marketCap:  12 },
  { symbol: 'BKNG',  name: 'Booking Holdings',           marketCap: 165 },
  { symbol: 'CCL',   name: 'Carnival Corporation',       marketCap:  25 },
  { symbol: 'CVNA',  name: 'Carvana',                    marketCap:  35 },
  { symbol: 'DASH',  name: 'DoorDash',                   marketCap:  60 },
  { symbol: 'DECK',  name: 'Deckers Brands',             marketCap:  15 },
  { symbol: 'DHI',   name: 'D.R. Horton',                marketCap:  42 },
  { symbol: 'DPZ',   name: "Domino's Pizza",             marketCap:  15 },
  { symbol: 'DRI',   name: 'Darden Restaurants',         marketCap:  18 },
  { symbol: 'EBAY',  name: 'eBay',                       marketCap:  30 },
  { symbol: 'EXPE',  name: 'Expedia Group',              marketCap:  20 },
  { symbol: 'F',     name: 'Ford Motor',                 marketCap:  40 },
  { symbol: 'GM',    name: 'General Motors',             marketCap:  50 },
  { symbol: 'GPC',   name: 'Genuine Parts',              marketCap:  14 },
  { symbol: 'GRMN',  name: 'Garmin',                     marketCap:  28 },
  { symbol: 'HAS',   name: 'Hasbro',                     marketCap:   8 },
  { symbol: 'HD',    name: 'Home Depot',                 marketCap: 360 },
  { symbol: 'HLT',   name: 'Hilton Worldwide',           marketCap:  55 },
  { symbol: 'LEN',   name: 'Lennar',                     marketCap:  30 },
  { symbol: 'LOW',   name: "Lowe's",                     marketCap: 130 },
  { symbol: 'LULU',  name: 'Lululemon',                  marketCap:  30 },
  { symbol: 'LVS',   name: 'Las Vegas Sands',            marketCap:  30 },
  { symbol: 'MAR',   name: 'Marriott International',     marketCap:  65 },
  { symbol: 'MCD',   name: "McDonald's",                 marketCap: 205 },
  { symbol: 'MGM',   name: 'MGM Resorts',                marketCap:  12 },
  { symbol: 'NKE',   name: 'Nike',                       marketCap:  72 },
  { symbol: 'NCLH',  name: 'Norwegian Cruise Line',      marketCap:   9 },
  { symbol: 'NVR',   name: 'NVR',                        marketCap:  20 },
  { symbol: 'ORLY',  name: "O'Reilly Automotive",        marketCap:  68 },
  { symbol: 'POOL',  name: 'Pool Corporation',           marketCap:  14 },
  { symbol: 'RCL',   name: 'Royal Caribbean',            marketCap:  52 },
  { symbol: 'RL',    name: 'Ralph Lauren',               marketCap:  10 },
  { symbol: 'ROST',  name: 'Ross Stores',                marketCap:  46 },
  { symbol: 'TJX',   name: 'TJX Companies',              marketCap: 130 },
  { symbol: 'TKO',   name: 'TKO Group Holdings',         marketCap:  25 },
  { symbol: 'TPR',   name: 'Tapestry',                   marketCap:   8 },
  { symbol: 'TSLA',  name: 'Tesla',                      marketCap: 1100 },
  { symbol: 'TTWO',  name: 'Take-Two Interactive',       marketCap:  30 },
  { symbol: 'YUM',   name: 'Yum! Brands',                marketCap:  30 },

  // ── Consumer Staples ──────────────────────────────────────────────────────
  { symbol: 'ADM',   name: 'Archer-Daniels-Midland',     marketCap:  18 },
  { symbol: 'BG',    name: 'Bunge Global',               marketCap:  10 },
  { symbol: 'CAG',   name: 'Conagra Brands',             marketCap:  12 },
  { symbol: 'CASY',  name: "Casey's General Stores",     marketCap:  12 },
  { symbol: 'CL',    name: 'Colgate-Palmolive',          marketCap:  58 },
  { symbol: 'CLX',   name: 'Clorox',                     marketCap:  16 },
  { symbol: 'COST',  name: 'Costco',                     marketCap: 480 },
  { symbol: 'CPB',   name: "Campbell's",                 marketCap:  10 },
  { symbol: 'DG',    name: 'Dollar General',             marketCap:  14 },
  { symbol: 'DLTR',  name: 'Dollar Tree',                marketCap:  15 },
  { symbol: 'EL',    name: 'Estée Lauder',               marketCap:  22 },
  { symbol: 'GIS',   name: 'General Mills',              marketCap:  30 },
  { symbol: 'HRL',   name: 'Hormel Foods',               marketCap:  12 },
  { symbol: 'HSY',   name: 'Hershey',                    marketCap:  24 },
  { symbol: 'KDP',   name: 'Keurig Dr Pepper',           marketCap:  36 },
  { symbol: 'KHC',   name: 'Kraft Heinz',                marketCap:  28 },
  { symbol: 'KMB',   name: 'Kimberly-Clark',             marketCap:  42 },
  { symbol: 'KO',    name: 'Coca-Cola',                  marketCap: 310 },
  { symbol: 'KR',    name: 'Kroger',                     marketCap:  40 },
  { symbol: 'KVUE',  name: 'Kenvue',                     marketCap:  38 },
  { symbol: 'MDLZ',  name: 'Mondelez International',     marketCap:  80 },
  { symbol: 'MKC',   name: 'McCormick',                  marketCap:  18 },
  { symbol: 'MNST',  name: 'Monster Beverage',           marketCap:  46 },
  { symbol: 'MO',    name: 'Altria',                     marketCap:  82 },
  { symbol: 'PEP',   name: 'PepsiCo',                    marketCap: 200 },
  { symbol: 'PG',    name: 'Procter & Gamble',           marketCap: 355 },
  { symbol: 'PM',    name: 'Philip Morris International', marketCap: 230 },
  { symbol: 'STZ',   name: 'Constellation Brands',       marketCap:  38 },
  { symbol: 'SYY',   name: 'Sysco',                      marketCap:  33 },
  { symbol: 'TAP',   name: 'Molson Coors',               marketCap:  10 },
  { symbol: 'TSN',   name: 'Tyson Foods',                marketCap:  18 },
  { symbol: 'WMT',   name: 'Walmart',                    marketCap: 760 },

  // ── Energy ────────────────────────────────────────────────────────────────
  { symbol: 'APA',   name: 'APA Corporation',            marketCap:   8 },
  { symbol: 'BKR',   name: 'Baker Hughes',               marketCap:  35 },
  { symbol: 'COP',   name: 'ConocoPhillips',             marketCap: 115 },
  { symbol: 'CVX',   name: 'Chevron',                    marketCap: 270 },
  { symbol: 'DVN',   name: 'Devon Energy',               marketCap:  12 },
  { symbol: 'EOG',   name: 'EOG Resources',              marketCap:  52 },
  { symbol: 'EQT',   name: 'EQT Corporation',            marketCap:  18 },
  { symbol: 'EXE',   name: 'Expand Energy',              marketCap:  12 },
  { symbol: 'FANG',  name: 'Diamondback Energy',         marketCap:  28 },
  { symbol: 'HAL',   name: 'Halliburton',                marketCap:  25 },
  { symbol: 'KMI',   name: 'Kinder Morgan',              marketCap:  25 },
  { symbol: 'MPC',   name: 'Marathon Petroleum',         marketCap:  42 },
  { symbol: 'OKE',   name: 'Oneok',                      marketCap:  38 },
  { symbol: 'OXY',   name: 'Occidental Petroleum',       marketCap:  42 },
  { symbol: 'PSX',   name: 'Phillips 66',                marketCap:  40 },
  { symbol: 'SLB',   name: 'SLB',                        marketCap:  50 },
  { symbol: 'TPL',   name: 'Texas Pacific Land',         marketCap:  22 },
  { symbol: 'TRGP',  name: 'Targa Resources',            marketCap:  35 },
  { symbol: 'VLO',   name: 'Valero Energy',              marketCap:  35 },
  { symbol: 'XOM',   name: 'ExxonMobil',                 marketCap: 465 },

  // ── Financials ────────────────────────────────────────────────────────────
  { symbol: 'ACGL',  name: 'Arch Capital Group',         marketCap:  35 },
  { symbol: 'AFL',   name: 'Aflac',                      marketCap:  48 },
  { symbol: 'AIG',   name: 'AIG',                        marketCap:  48 },
  { symbol: 'AIZ',   name: 'Assurant',                   marketCap:  10 },
  { symbol: 'AJG',   name: 'Arthur J. Gallagher',        marketCap:  60 },
  { symbol: 'ALL',   name: 'Allstate',                   marketCap:  55 },
  { symbol: 'AMP',   name: 'Ameriprise Financial',       marketCap:  45 },
  { symbol: 'APO',   name: 'Apollo Global Management',   marketCap:  85 },
  { symbol: 'ARES',  name: 'Ares Management',            marketCap:  55 },
  { symbol: 'AXP',   name: 'American Express',           marketCap: 200 },
  { symbol: 'BAC',   name: 'Bank of America',            marketCap: 330 },
  { symbol: 'BEN',   name: 'Franklin Resources',         marketCap:  12 },
  { symbol: 'BK',    name: 'BNY Mellon',                 marketCap:  58 },
  { symbol: 'BLK',   name: 'BlackRock',                  marketCap: 155 },
  { symbol: 'BRO',   name: 'Brown & Brown',              marketCap:  28 },
  { symbol: 'BX',    name: 'Blackstone',                 marketCap: 165 },
  { symbol: 'C',     name: 'Citigroup',                  marketCap: 120 },
  { symbol: 'CB',    name: 'Chubb',                      marketCap: 110 },
  { symbol: 'CBOE',  name: 'Cboe Global Markets',        marketCap:  22 },
  { symbol: 'CFG',   name: 'Citizens Financial',         marketCap:  18 },
  { symbol: 'CINF',  name: 'Cincinnati Financial',       marketCap:  20 },
  { symbol: 'CME',   name: 'CME Group',                  marketCap:  80 },
  { symbol: 'COIN',  name: 'Coinbase',                   marketCap:  55 },
  { symbol: 'COF',   name: 'Capital One',                marketCap:  75 },
  { symbol: 'CPAY',  name: 'Corpay',                     marketCap:  22 },
  { symbol: 'EG',    name: 'Everest Group',              marketCap:  15 },
  { symbol: 'ERIE',  name: 'Erie Indemnity',             marketCap:  22 },
  { symbol: 'FDS',   name: 'FactSet Research',           marketCap:  16 },
  { symbol: 'FIS',   name: 'Fidelity National Info',     marketCap:  18 },
  { symbol: 'FISV',  name: 'Fiserv',                     marketCap:  90 },
  { symbol: 'FITB',  name: 'Fifth Third Bancorp',        marketCap:  22 },
  { symbol: 'GL',    name: 'Globe Life',                 marketCap:  10 },
  { symbol: 'GPN',   name: 'Global Payments',            marketCap:  22 },
  { symbol: 'GS',    name: 'Goldman Sachs',              marketCap: 195 },
  { symbol: 'HIG',   name: 'Hartford Financial',         marketCap:  35 },
  { symbol: 'HBAN',  name: 'Huntington Bancshares',      marketCap:  20 },
  { symbol: 'IBKR',  name: 'Interactive Brokers',        marketCap:  30 },
  { symbol: 'ICE',   name: 'Intercontinental Exchange',  marketCap:  80 },
  { symbol: 'IVZ',   name: 'Invesco',                    marketCap:   8 },
  { symbol: 'JKHY',  name: 'Jack Henry & Associates',    marketCap:  14 },
  { symbol: 'JPM',   name: 'JPMorgan Chase',             marketCap: 740 },
  { symbol: 'KEY',   name: 'KeyCorp',                    marketCap:  18 },
  { symbol: 'KKR',   name: 'KKR & Co.',                  marketCap: 125 },
  { symbol: 'L',     name: 'Loews Corporation',          marketCap:  18 },
  { symbol: 'MCO',   name: "Moody's",                    marketCap:  80 },
  { symbol: 'MET',   name: 'MetLife',                    marketCap:  52 },
  { symbol: 'MMC',   name: 'Marsh McLennan',             marketCap:  95 },
  { symbol: 'MS',    name: 'Morgan Stanley',             marketCap: 180 },
  { symbol: 'MSCI',  name: 'MSCI',                       marketCap:  40 },
  { symbol: 'MTB',   name: 'M&T Bank',                   marketCap:  25 },
  { symbol: 'NDAQ',  name: 'Nasdaq',                     marketCap:  45 },
  { symbol: 'NTRS',  name: 'Northern Trust',             marketCap:  18 },
  { symbol: 'PFG',   name: 'Principal Financial',        marketCap:  18 },
  { symbol: 'PNC',   name: 'PNC Financial',              marketCap:  65 },
  { symbol: 'PRU',   name: 'Prudential Financial',       marketCap:  38 },
  { symbol: 'PYPL',  name: 'PayPal',                     marketCap:  65 },
  { symbol: 'RF',    name: 'Regions Financial',          marketCap:  20 },
  { symbol: 'RJF',   name: 'Raymond James',              marketCap:  28 },
  { symbol: 'SCHW',  name: 'Charles Schwab',             marketCap: 130 },
  { symbol: 'SPGI',  name: 'S&P Global',                 marketCap: 145 },
  { symbol: 'STT',   name: 'State Street',               marketCap:  25 },
  { symbol: 'SYF',   name: 'Synchrony Financial',        marketCap:  20 },
  { symbol: 'TFC',   name: 'Truist Financial',           marketCap:  52 },
  { symbol: 'TROW',  name: 'T. Rowe Price',              marketCap:  22 },
  { symbol: 'TRV',   name: 'Travelers',                  marketCap:  52 },
  { symbol: 'USB',   name: 'U.S. Bancorp',               marketCap:  68 },
  { symbol: 'V',     name: 'Visa',                       marketCap: 620 },
  { symbol: 'WFC',   name: 'Wells Fargo',                marketCap: 225 },
  { symbol: 'WRB',   name: 'W.R. Berkley',               marketCap:  22 },
  { symbol: 'WTW',   name: 'Willis Towers Watson',       marketCap:  28 },
  { symbol: 'XYZ',   name: 'Block',                      marketCap:  42 },

  // ── Health Care ───────────────────────────────────────────────────────────
  { symbol: 'A',     name: 'Agilent Technologies',       marketCap:  22 },
  { symbol: 'ABT',   name: 'Abbott Laboratories',        marketCap: 195 },
  { symbol: 'ABBV',  name: 'AbbVie',                     marketCap: 300 },
  { symbol: 'ALGN',  name: 'Align Technology',           marketCap:  12 },
  { symbol: 'AMGN',  name: 'Amgen',                      marketCap: 150 },
  { symbol: 'BAX',   name: 'Baxter International',       marketCap:  10 },
  { symbol: 'BDX',   name: 'Becton Dickinson',           marketCap:  65 },
  { symbol: 'BIIB',  name: 'Biogen',                     marketCap:  25 },
  { symbol: 'BMY',   name: 'Bristol Myers Squibb',       marketCap: 120 },
  { symbol: 'BSX',   name: 'Boston Scientific',          marketCap: 120 },
  { symbol: 'CAH',   name: 'Cardinal Health',            marketCap:  22 },
  { symbol: 'CI',    name: 'Cigna',                      marketCap:  80 },
  { symbol: 'CNC',   name: 'Centene',                    marketCap:  25 },
  { symbol: 'COO',   name: 'Cooper Companies',           marketCap:  14 },
  { symbol: 'COR',   name: 'Cencora',                    marketCap:  42 },
  { symbol: 'CRL',   name: 'Charles River Laboratories', marketCap:   6 },
  { symbol: 'CVS',   name: 'CVS Health',                 marketCap:  75 },
  { symbol: 'DHR',   name: 'Danaher',                    marketCap: 155 },
  { symbol: 'DGX',   name: 'Quest Diagnostics',          marketCap:  18 },
  { symbol: 'DVA',   name: 'DaVita',                     marketCap:  10 },
  { symbol: 'DXCM',  name: 'Dexcom',                     marketCap:  22 },
  { symbol: 'ELV',   name: 'Elevance Health',            marketCap:  68 },
  { symbol: 'EW',    name: 'Edwards Lifesciences',       marketCap:  35 },
  { symbol: 'GEHC',  name: 'GE HealthCare',              marketCap:  35 },
  { symbol: 'GILD',  name: 'Gilead Sciences',            marketCap: 105 },
  { symbol: 'HCA',   name: 'HCA Healthcare',             marketCap:  62 },
  { symbol: 'HSIC',  name: 'Henry Schein',               marketCap:   8 },
  { symbol: 'HUM',   name: 'Humana',                     marketCap:  38 },
  { symbol: 'IDXX',  name: 'Idexx Laboratories',         marketCap:  38 },
  { symbol: 'INCY',  name: 'Incyte',                     marketCap:  14 },
  { symbol: 'IQV',   name: 'IQVIA',                      marketCap:  38 },
  { symbol: 'ISRG',  name: 'Intuitive Surgical',         marketCap: 185 },
  { symbol: 'JNJ',   name: 'Johnson & Johnson',          marketCap: 380 },
  { symbol: 'LH',    name: 'Labcorp',                    marketCap:  15 },
  { symbol: 'LLY',   name: 'Eli Lilly',                  marketCap: 700 },
  { symbol: 'MCK',   name: 'McKesson',                   marketCap:  72 },
  { symbol: 'MDT',   name: 'Medtronic',                  marketCap: 105 },
  { symbol: 'MRK',   name: 'Merck',                      marketCap: 210 },
  { symbol: 'MRNA',  name: 'Moderna',                    marketCap:  16 },
  { symbol: 'MTD',   name: 'Mettler-Toledo',             marketCap:  22 },
  { symbol: 'PFE',   name: 'Pfizer',                     marketCap: 145 },
  { symbol: 'PODD',  name: 'Insulet',                    marketCap:  10 },
  { symbol: 'REGN',  name: 'Regeneron',                  marketCap:  55 },
  { symbol: 'RMD',   name: 'ResMed',                     marketCap:  30 },
  { symbol: 'RVTY',  name: 'Revvity',                    marketCap:  10 },
  { symbol: 'SOLV',  name: 'Solventum',                  marketCap:  12 },
  { symbol: 'STE',   name: 'Steris',                     marketCap:  18 },
  { symbol: 'SYK',   name: 'Stryker',                    marketCap: 135 },
  { symbol: 'TECH',  name: 'Bio-Techne',                 marketCap:   6 },
  { symbol: 'TMO',   name: 'Thermo Fisher Scientific',   marketCap: 190 },
  { symbol: 'UHS',   name: 'Universal Health Services',  marketCap:  14 },
  { symbol: 'VRTX',  name: 'Vertex Pharmaceuticals',     marketCap: 115 },
  { symbol: 'VTRS',  name: 'Viatris',                    marketCap:  12 },
  { symbol: 'ZBH',   name: 'Zimmer Biomet',              marketCap:  10 },
  { symbol: 'ZTS',   name: 'Zoetis',                     marketCap:  62 },

  // ── Industrials ───────────────────────────────────────────────────────────
  { symbol: 'ADP',   name: 'Automatic Data Processing',  marketCap: 105 },
  { symbol: 'ALLE',  name: 'Allegion',                   marketCap:  10 },
  { symbol: 'AME',   name: 'Ametek',                     marketCap:  38 },
  { symbol: 'AOS',   name: 'A.O. Smith',                 marketCap:   8 },
  { symbol: 'AXON',  name: 'Axon Enterprise',            marketCap:  45 },
  { symbol: 'BA',    name: 'Boeing',                     marketCap: 130 },
  { symbol: 'BLDR',  name: 'Builders FirstSource',       marketCap:  18 },
  { symbol: 'BR',    name: 'Broadridge Financial',       marketCap:  25 },
  { symbol: 'CARR',  name: 'Carrier Global',             marketCap:  55 },
  { symbol: 'CAT',   name: 'Caterpillar',                marketCap: 175 },
  { symbol: 'CHRW',  name: 'C.H. Robinson',              marketCap:  12 },
  { symbol: 'CMI',   name: 'Cummins',                    marketCap:  38 },
  { symbol: 'CPRT',  name: 'Copart',                     marketCap:  50 },
  { symbol: 'CSX',   name: 'CSX',                        marketCap:  62 },
  { symbol: 'DAL',   name: 'Delta Air Lines',            marketCap:  18 },
  { symbol: 'DE',    name: 'Deere & Company',            marketCap: 115 },
  { symbol: 'DOV',   name: 'Dover',                      marketCap:  22 },
  { symbol: 'EFX',   name: 'Equifax',                    marketCap:  28 },
  { symbol: 'EME',   name: 'Emcor',                      marketCap:  18 },
  { symbol: 'EMR',   name: 'Emerson Electric',           marketCap:  65 },
  { symbol: 'EXPD',  name: 'Expeditors International',   marketCap:  16 },
  { symbol: 'FAST',  name: 'Fastenal',                   marketCap:  38 },
  { symbol: 'FDX',   name: 'FedEx',                      marketCap:  55 },
  { symbol: 'FIX',   name: 'Comfort Systems USA',        marketCap:  10 },
  { symbol: 'FTV',   name: 'Fortive',                    marketCap:  22 },
  { symbol: 'GD',    name: 'General Dynamics',           marketCap:  75 },
  { symbol: 'GE',    name: 'GE Aerospace',               marketCap: 220 },
  { symbol: 'GEV',   name: 'GE Vernova',                 marketCap:  55 },
  { symbol: 'GNRC',  name: 'Generac',                    marketCap:   8 },
  { symbol: 'GWW',   name: 'W.W. Grainger',              marketCap:  42 },
  { symbol: 'HII',   name: 'Huntington Ingalls',         marketCap:   8 },
  { symbol: 'HON',   name: 'Honeywell',                  marketCap: 155 },
  { symbol: 'HUBB',  name: 'Hubbell',                    marketCap:  16 },
  { symbol: 'HWM',   name: 'Howmet Aerospace',           marketCap:  35 },
  { symbol: 'IEX',   name: 'IDEX Corporation',           marketCap:  16 },
  { symbol: 'IR',    name: 'Ingersoll Rand',             marketCap:  30 },
  { symbol: 'ITW',   name: 'Illinois Tool Works',        marketCap:  72 },
  { symbol: 'J',     name: 'Jacobs Solutions',           marketCap:  14 },
  { symbol: 'JBHT',  name: 'J.B. Hunt Transport',        marketCap:  18 },
  { symbol: 'JCI',   name: 'Johnson Controls',           marketCap:  50 },
  { symbol: 'LDOS',  name: 'Leidos',                     marketCap:  18 },
  { symbol: 'LHX',   name: 'L3Harris Technologies',      marketCap:  45 },
  { symbol: 'LII',   name: 'Lennox International',       marketCap:  22 },
  { symbol: 'LMT',   name: 'Lockheed Martin',            marketCap: 120 },
  { symbol: 'MAS',   name: 'Masco',                      marketCap:  16 },
  { symbol: 'MMM',   name: '3M',                         marketCap:  65 },
  { symbol: 'NDSN',  name: 'Nordson',                    marketCap:   8 },
  { symbol: 'NOC',   name: 'Northrop Grumman',           marketCap:  65 },
  { symbol: 'NSC',   name: 'Norfolk Southern',           marketCap:  55 },
  { symbol: 'ODFL',  name: 'Old Dominion Freight',       marketCap:  38 },
  { symbol: 'OTIS',  name: 'Otis Worldwide',             marketCap:  30 },
  { symbol: 'PCAR',  name: 'Paccar',                     marketCap:  38 },
  { symbol: 'PAYX',  name: 'Paychex',                    marketCap:  52 },
  { symbol: 'PH',    name: 'Parker Hannifin',            marketCap:  80 },
  { symbol: 'PNR',   name: 'Pentair',                    marketCap:  12 },
  { symbol: 'PWR',   name: 'Quanta Services',            marketCap:  42 },
  { symbol: 'ROK',   name: 'Rockwell Automation',        marketCap:  22 },
  { symbol: 'ROL',   name: 'Rollins',                    marketCap:  22 },
  { symbol: 'ROP',   name: 'Roper Technologies',         marketCap:  52 },
  { symbol: 'RTX',   name: 'RTX Corporation',            marketCap: 160 },
  { symbol: 'SNA',   name: 'Snap-on',                    marketCap:  16 },
  { symbol: 'SW',    name: 'Smurfit Westrock',           marketCap:  22 },
  { symbol: 'SWK',   name: 'Stanley Black & Decker',     marketCap:  14 },
  { symbol: 'TDG',   name: 'TransDigm Group',            marketCap:  65 },
  { symbol: 'TDY',   name: 'Teledyne Technologies',      marketCap:  18 },
  { symbol: 'TEL',   name: 'TE Connectivity',            marketCap:  40 },
  { symbol: 'TT',    name: 'Trane Technologies',         marketCap:  65 },
  { symbol: 'TXT',   name: 'Textron',                    marketCap:  12 },
  { symbol: 'UAL',   name: 'United Airlines',            marketCap:  22 },
  { symbol: 'UNP',   name: 'Union Pacific',              marketCap: 155 },
  { symbol: 'UPS',   name: 'United Parcel Service',      marketCap:  85 },
  { symbol: 'URI',   name: 'United Rentals',             marketCap:  38 },
  { symbol: 'VLTO',  name: 'Veralto',                    marketCap:  16 },
  { symbol: 'WAB',   name: 'Wabtec',                     marketCap:  22 },

  // ── Information Technology ────────────────────────────────────────────────
  { symbol: 'AAPL',  name: 'Apple',                      marketCap: 3200 },
  { symbol: 'ACN',   name: 'Accenture',                  marketCap: 195 },
  { symbol: 'ADBE',  name: 'Adobe',                      marketCap: 155 },
  { symbol: 'ADI',   name: 'Analog Devices',             marketCap:  95 },
  { symbol: 'ADSK',  name: 'Autodesk',                   marketCap:  60 },
  { symbol: 'AKAM',  name: 'Akamai Technologies',        marketCap:  14 },
  { symbol: 'AMD',   name: 'Advanced Micro Devices',     marketCap: 230 },
  { symbol: 'AMAT',  name: 'Applied Materials',          marketCap: 165 },
  { symbol: 'ANET',  name: 'Arista Networks',            marketCap: 100 },
  { symbol: 'APP',   name: 'AppLovin',                   marketCap: 115 },
  { symbol: 'APH',   name: 'Amphenol',                   marketCap:  85 },
  { symbol: 'AVGO',  name: 'Broadcom',                   marketCap: 910 },
  { symbol: 'CDNS',  name: 'Cadence Design Systems',     marketCap:  75 },
  { symbol: 'CIEN',  name: 'Ciena',                      marketCap:   8 },
  { symbol: 'COHR',  name: 'Coherent',                   marketCap:  10 },
  { symbol: 'CRM',   name: 'Salesforce',                 marketCap: 230 },
  { symbol: 'CRWD',  name: 'CrowdStrike',                marketCap: 100 },
  { symbol: 'CSCO',  name: 'Cisco',                      marketCap: 245 },
  { symbol: 'CTSH',  name: 'Cognizant',                  marketCap:  35 },
  { symbol: 'DDOG',  name: 'Datadog',                    marketCap:  45 },
  { symbol: 'DELL',  name: 'Dell Technologies',          marketCap:  60 },
  { symbol: 'FFIV',  name: 'F5',                         marketCap:  12 },
  { symbol: 'FICO',  name: 'Fair Isaac (FICO)',           marketCap:  52 },
  { symbol: 'FSLR',  name: 'First Solar',                marketCap:  14 },
  { symbol: 'FTNT',  name: 'Fortinet',                   marketCap:  72 },
  { symbol: 'GEN',   name: 'Gen Digital',                marketCap:  16 },
  { symbol: 'GDDY',  name: 'GoDaddy',                    marketCap:  28 },
  { symbol: 'GLW',   name: 'Corning',                    marketCap:  30 },
  { symbol: 'HPE',   name: 'Hewlett Packard Enterprise', marketCap:  22 },
  { symbol: 'HPQ',   name: 'HP',                         marketCap:  28 },
  { symbol: 'IBM',   name: 'IBM',                        marketCap: 250 },
  { symbol: 'INTC',  name: 'Intel',                      marketCap:  95 },
  { symbol: 'INTU',  name: 'Intuit',                     marketCap: 165 },
  { symbol: 'IT',    name: 'Gartner',                    marketCap:  30 },
  { symbol: 'JBL',   name: 'Jabil',                      marketCap:   8 },
  { symbol: 'KEYS',  name: 'Keysight Technologies',      marketCap:  18 },
  { symbol: 'KLAC',  name: 'KLA Corporation',            marketCap:  95 },
  { symbol: 'LITE',  name: 'Lumentum',                   marketCap:   4 },
  { symbol: 'LRCX',  name: 'Lam Research',               marketCap:  85 },
  { symbol: 'MCHP',  name: 'Microchip Technology',       marketCap:  30 },
  { symbol: 'MPWR',  name: 'Monolithic Power Systems',   marketCap:  22 },
  { symbol: 'MSI',   name: 'Motorola Solutions',         marketCap:  68 },
  { symbol: 'MU',    name: 'Micron Technology',          marketCap: 115 },
  { symbol: 'MSFT',  name: 'Microsoft',                  marketCap: 3100 },
  { symbol: 'NTAP',  name: 'NetApp',                     marketCap:  22 },
  { symbol: 'NVDA',  name: 'Nvidia',                     marketCap: 3300 },
  { symbol: 'NXPI',  name: 'NXP Semiconductors',         marketCap:  42 },
  { symbol: 'ON',    name: 'ON Semiconductor',           marketCap:  18 },
  { symbol: 'ORCL',  name: 'Oracle',                     marketCap: 505 },
  { symbol: 'PANW',  name: 'Palo Alto Networks',         marketCap: 115 },
  { symbol: 'PLTR',  name: 'Palantir Technologies',      marketCap: 280 },
  { symbol: 'QCOM',  name: 'Qualcomm',                   marketCap: 165 },
  { symbol: 'SMCI',  name: 'Super Micro Computer',       marketCap:  28 },
  { symbol: 'SNDK',  name: 'SanDisk',                    marketCap:  20 },
  { symbol: 'SNPS',  name: 'Synopsys',                   marketCap:  75 },
  { symbol: 'SWKS',  name: 'Skyworks Solutions',         marketCap:  12 },
  { symbol: 'TER',   name: 'Teradyne',                   marketCap:  14 },
  { symbol: 'TRMB',  name: 'Trimble',                    marketCap:  16 },
  { symbol: 'TXN',   name: 'Texas Instruments',          marketCap: 165 },
  { symbol: 'TYL',   name: 'Tyler Technologies',         marketCap:  22 },
  { symbol: 'VRSN',  name: 'Verisign',                   marketCap:  16 },
  { symbol: 'WDC',   name: 'Western Digital',            marketCap:  22 },

  // ── Materials ─────────────────────────────────────────────────────────────
  { symbol: 'ALB',   name: 'Albemarle',                  marketCap:   5 },
  { symbol: 'AMCR',  name: 'Amcor',                      marketCap:  12 },
  { symbol: 'APD',   name: 'Air Products',               marketCap:  50 },
  { symbol: 'AVY',   name: 'Avery Dennison',             marketCap:  14 },
  { symbol: 'BALL',  name: 'Ball Corporation',           marketCap:  16 },
  { symbol: 'CF',    name: 'CF Industries',              marketCap:  12 },
  { symbol: 'CRH',   name: 'CRH',                        marketCap:  65 },
  { symbol: 'CTVA',  name: 'Corteva',                    marketCap:  22 },
  { symbol: 'DD',    name: 'DuPont',                     marketCap:  20 },
  { symbol: 'DOW',   name: 'Dow',                        marketCap:  32 },
  { symbol: 'ECL',   name: 'Ecolab',                     marketCap:  62 },
  { symbol: 'FCX',   name: 'Freeport-McMoRan',           marketCap:  58 },
  { symbol: 'IFF',   name: 'Intl Flavors & Fragrances',  marketCap:  15 },
  { symbol: 'IP',    name: 'International Paper',        marketCap:  16 },
  { symbol: 'LIN',   name: 'Linde',                      marketCap: 230 },
  { symbol: 'LYB',   name: 'LyondellBasell',             marketCap:  12 },
  { symbol: 'MLM',   name: 'Martin Marietta Materials',  marketCap:  28 },
  { symbol: 'MOS',   name: 'Mosaic',                     marketCap:   8 },
  { symbol: 'NEM',   name: 'Newmont',                    marketCap:  50 },
  { symbol: 'NUE',   name: 'Nucor',                      marketCap:  22 },
  { symbol: 'PKG',   name: 'Packaging Corp of America',  marketCap:  14 },
  { symbol: 'PPG',   name: 'PPG Industries',             marketCap:  28 },
  { symbol: 'STLD',  name: 'Steel Dynamics',             marketCap:  18 },
  { symbol: 'VMC',   name: 'Vulcan Materials',           marketCap:  28 },

  // ── Real Estate ───────────────────────────────────────────────────────────
  { symbol: 'AMT',   name: 'American Tower',             marketCap:  92 },
  { symbol: 'ARE',   name: 'Alexandria Real Estate',     marketCap:  12 },
  { symbol: 'AVB',   name: 'AvalonBay Communities',      marketCap:  28 },
  { symbol: 'BXP',   name: 'BXP',                        marketCap:  10 },
  { symbol: 'CCI',   name: 'Crown Castle',               marketCap:  42 },
  { symbol: 'CBRE',  name: 'CBRE Group',                 marketCap:  35 },
  { symbol: 'CSGP',  name: 'CoStar Group',               marketCap:  28 },
  { symbol: 'CPT',   name: 'Camden Property Trust',      marketCap:  12 },
  { symbol: 'DLR',   name: 'Digital Realty Trust',       marketCap:  48 },
  { symbol: 'DOC',   name: 'Healthpeak Properties',      marketCap:  12 },
  { symbol: 'EQIX',  name: 'Equinix',                    marketCap:  80 },
  { symbol: 'EQR',   name: 'Equity Residential',         marketCap:  22 },
  { symbol: 'ESS',   name: 'Essex Property Trust',       marketCap:  16 },
  { symbol: 'EXR',   name: 'Extra Space Storage',        marketCap:  32 },
  { symbol: 'FRT',   name: 'Federal Realty',             marketCap:   8 },
  { symbol: 'HST',   name: 'Host Hotels & Resorts',      marketCap:  12 },
  { symbol: 'INVH',  name: 'Invitation Homes',           marketCap:  18 },
  { symbol: 'IRM',   name: 'Iron Mountain',              marketCap:  30 },
  { symbol: 'KIM',   name: 'Kimco Realty',               marketCap:  14 },
  { symbol: 'MAA',   name: 'Mid-America Apartment',      marketCap:  16 },
  { symbol: 'O',     name: 'Realty Income',              marketCap:  50 },
  { symbol: 'PLD',   name: 'Prologis',                   marketCap: 100 },
  { symbol: 'PSA',   name: 'Public Storage',             marketCap:  52 },
  { symbol: 'REG',   name: 'Regency Centers',            marketCap:  12 },
  { symbol: 'SBAC',  name: 'SBA Communications',         marketCap:  22 },
  { symbol: 'UDR',   name: 'UDR',                        marketCap:  12 },
  { symbol: 'VICI',  name: 'VICI Properties',            marketCap:  32 },
  { symbol: 'VTR',   name: 'Ventas',                     marketCap:  20 },
  { symbol: 'WELL',  name: 'Welltower',                  marketCap:  65 },
  { symbol: 'WY',    name: 'Weyerhaeuser',               marketCap:  18 },

  // ── Utilities ─────────────────────────────────────────────────────────────
  { symbol: 'AEE',   name: 'Ameren',                     marketCap:  22 },
  { symbol: 'AEP',   name: 'American Electric Power',    marketCap:  52 },
  { symbol: 'AES',   name: 'AES Corporation',            marketCap:  12 },
  { symbol: 'ATO',   name: 'Atmos Energy',               marketCap:  18 },
  { symbol: 'AWK',   name: 'American Water Works',       marketCap:  25 },
  { symbol: 'CEG',   name: 'Constellation Energy',       marketCap:  62 },
  { symbol: 'CMS',   name: 'CMS Energy',                 marketCap:  20 },
  { symbol: 'CNP',   name: 'CenterPoint Energy',         marketCap:  20 },
  { symbol: 'D',     name: 'Dominion Energy',            marketCap:  45 },
  { symbol: 'DTE',   name: 'DTE Energy',                 marketCap:  22 },
  { symbol: 'DUK',   name: 'Duke Energy',                marketCap:  85 },
  { symbol: 'ED',    name: 'Consolidated Edison',        marketCap:  30 },
  { symbol: 'EIX',   name: 'Edison International',       marketCap:  22 },
  { symbol: 'ES',    name: 'Eversource Energy',          marketCap:  18 },
  { symbol: 'ETR',   name: 'Entergy',                    marketCap:  22 },
  { symbol: 'EVRG',  name: 'Evergy',                     marketCap:   8 },
  { symbol: 'EXC',   name: 'Exelon',                     marketCap:  42 },
  { symbol: 'FE',    name: 'FirstEnergy',                marketCap:  22 },
  { symbol: 'LNT',   name: 'Alliant Energy',             marketCap:  14 },
  { symbol: 'NEE',   name: 'NextEra Energy',             marketCap: 145 },
  { symbol: 'NI',    name: 'NiSource',                   marketCap:  12 },
  { symbol: 'NRG',   name: 'NRG Energy',                 marketCap:  12 },
  { symbol: 'PCG',   name: 'PG&E Corporation',           marketCap:  48 },
  { symbol: 'PEG',   name: 'Public Service Enterprise',  marketCap:  32 },
  { symbol: 'PNW',   name: 'Pinnacle West Capital',      marketCap:   8 },
  { symbol: 'PPL',   name: 'PPL Corporation',            marketCap:  22 },
  { symbol: 'SRE',   name: 'Sempra',                     marketCap:  50 },
  { symbol: 'SO',    name: 'Southern Company',           marketCap:  88 },
  { symbol: 'VST',   name: 'Vistra',                     marketCap:  30 },
  { symbol: 'WEC',   name: 'WEC Energy Group',           marketCap:  30 },
  { symbol: 'XEL',   name: 'Xcel Energy',                marketCap:  38 },
];

// ── Randomisation ─────────────────────────────────────────────────────────────

/** In-place Fisher-Yates shuffle — unbiased, O(n). */
function fisherYates(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/**
 * Session queue — a freshly shuffled copy of the full list.
 * Guarantees every company appears once before any repeats.
 * Refills automatically when exhausted.
 */
let sessionQueue = [];

function refillQueue(skipSymbol = null) {
  const pool = skipSymbol
    ? SP500_COMPANIES.filter(c => c.symbol !== skipSymbol)
    : [...SP500_COMPANIES];
  sessionQueue = fisherYates(pool);
}

/** Draw one company from the queue, never returning `skipSymbol`. */
function drawOne(skipSymbol = null) {
  // Drop the skipped symbol from wherever it sits in the queue.
  if (skipSymbol) {
    const idx = sessionQueue.findIndex(c => c.symbol === skipSymbol);
    if (idx !== -1) sessionQueue.splice(idx, 1);
  }
  if (sessionQueue.length === 0) refillQueue(skipSymbol);
  return sessionQueue.shift();
}

/**
 * Returns { first, second } — two different companies.
 * Pass `excludeSymbol` to guarantee it doesn't appear in either slot
 * (used when the caller already holds that company as "current").
 */
export function getRandomHLPair(excludeSymbol = null) {
  const first  = drawOne(excludeSymbol);
  const second = drawOne(first.symbol);   // also excludes first
  return { first, second };
}

export function getCompanyBySymbol(symbol) {
  return SP500_COMPANIES.find(c => c.symbol === symbol);
}
